defaults:
  - drone: a300
  - task: goto
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled        
  - _self_

e:  no_name            
cm: SRTHover                 
B:  8192                
m:  301                 
seed: 1
v: false

log_dir: logs/${task.name}/${task.env.controller_type}_${drone.name}_${e}

hydra:
  run:
    dir: ${log_dir}
  job:
    chdir: false       
  output_subdir: null   

